export const eventTypes = {
    PDP_PAGE_VIEW: 'PDP_PAGE_VIEW',
    PLP_PAGE_VIEW: 'PLP_PAGE_VIEW',
    INTERACTION: 'INTERACTION',
    SEARCH: 'SEARCH',
    FORM_LOADED: 'FORM_LOADED',
    FORM_STARTED: 'FORM_STARTED',
    FORM_SUBMITTED: 'FORM_SUBMITTED'
};