/*! React Starter Kit | MIT License | http://www.reactstarterkit.com/ */

var keyMirror = require('fbjs/lib/keyMirror');

module.exports = keyMirror({
    API_ERROR: null,
    BOOTSTRAP: null,
    BOOTSTRAP_ERROR: null,
    CONFIG_ERROR: null,
    CHANGE_ROUTE: null,
    CLEAR_FAVOURITES: null,
    CLOSE_MODAL: null,
    CREATE_SEARCH_STATE: null,
    GET_ADJACENT_PROPERTY: null,
    GET_PROPERTIES: null,
    GET_PROPERTY: null,
    LOADING_API: null,
    LOADING_VIEW_START: null,
    LOADING_VIEW_END: null,
    LOADING_CONFIG: null,
    PLACES_ERROR: null,
    SET_CONFIG_ITEM: null,
    SET_LANG: null,
    SET_PARAM: null,
    SET_PARAMS: null,
    DELETE_PARAM: null,
    SET_PROPERTY_INDEX: null,
    SET_SEARCH_STATE: null,
    SET_PDF_PROPERTIES: null,
    PDF_PROPERTIES_UPDATED: null,
    SET_STATIC_MAPS: null,
    STATIC_MAPS_UPDATED: null,
    DELETE_SEARCH_STATE_ITEM: null,
    RESET_PROPERTIES: null,
    SIMPLE_USER_EVENT: null,
    STATE_CHANGE: null,
    UPDATE_APPLICATION_STATE: null,
    UPDATE_QUERY_PARAMS: null,
    SET_LISTINGS_META_TAGS: null,
    SET_FAVOURITES: null,
    TOGGLE_FAVOURITES: null,
    APPLICATION_ERROR: null,
    UPDATE_PROPERTIES_MAP: null,
    UPDATE_FETCH_MODE: null,
    UPDATE_ISAREA_SEARCH: null,
    GET_RELATED_PROPERTIES: null,
    FAILED_GET_RELATED_PROPERTIES: null,
    RELATED_PROPERTIES_UPDATED: null,
    GET_CHILD_PROPERTIES: null,
    FAILED_GET_CHILD_PROPERTIES: null,
    CHILD_PROPERTIES_UPDATED: null,
    GET_LISTING_COUNT: null,
    FAILED_GET_LISTING_COUNT: null,
    LISTING_COUNT_UPDATED: null
});
