module.exports = {
    carouselScroll: 'Scroll Through carousel',
    mapView: 'listings view switched to map view',
    listingsView: 'map view switched to list view',
    openMapMarker: 'map view viewed property summary',
    paginationNext: 'listings view view next',
    paginationPrev: 'listings view view previous',
    paginationAll: 'listings view view all',
    propertyNavNext: 'details view view next',
    propertyNavPrev: 'details view previous',
    propertyNavBack: 'details back to results',
    carouselPropertyLink: 'Viewed Property Details From Carousel',
    SearchWidgetSearch: 'Conducted search bar search',
    viewPropertyDetails: 'Viewed property details',
    searchPerformed: 'New search performed',
    viewPhoneNumber: 'listings view agent phone number',
    launchContactUs: 'listings view launch contact us',
    pdpLaunchContactUs: 'details view launch contact us',
    abandonContactUs: 'abandoned contact us',
    contactUsSuccessful: 'completed contact us',
    contactUsFailure: 'failed contact us',
    imageOpenLightbox: 'details launch image lightbox from image',
    floorplanOpenLightbox: 'details launch image lightbox from floorplan',
    floorplanPDF: 'details launch pdf floorplan',
    detailsViewEPC: 'details view EPC',
    detailsViewBrochure: 'details view brochure',
    viewWalkthrough: 'details view walkthrough',
    viewWebsite: 'details view Property Website',
    pdpLaunchStampDutyCalculator: 'details view stampDutyCalculator viewed',
    pdpCallToAction: 'details view misc call to action',
    siblingCarouselClickThru: 'sibling carousel click through',
    siblingCarouselScroll: 'sibling carousel scroll',
    listMapClearFilters: 'listings view clear filters',
    favouritePropertyAdded: 'Property added to favorites',
    favouritePropertyRemoved: 'Property removed from favorites',
    viewedFavourites: 'View favorites',
    exitedFavourites: 'Exit favorites',
    copiedShareFavouritesLink: 'Copy link from favorites share',
    clearedFavourites: 'Clear all favorites',
    clickedDownloadPdf: 'Click to generate PDF',
    childPropertyClickThru: 'child property click through',
    filterChange: 'Changing filter value',
    propertyTypeChange: 'PLPPropertyTypeChange'
};
